### ISSUE TITLE
fix style checks

### ISSUE THREAD

**Issue by jeremyschiemann** [LouisWirtz/tlwywgt#4]
fix errors raised by running flake8, mypy and pydocstyle

`poetry run flake8`

ref: see Makefile for all commands

DoD: pipeline checks are green

**Comment by LouisWirtz** [comment]
https://github.com/LouisWirtz/tlwywgt/commit/283017f31ec2679b7046497e4fa632084fa1b1b2

**Comment by jeremyschiemann** [comment]
lgtm
